config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :patients do
    get :registration_progress, on: :collection
  end
  resource :receptionist, only: %w[edit update], controller: :receptionist

  root 'patients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :email, :full_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  enum role: { receptionist: 0, doctor: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protected

  def user_not_authorized
    render file: "#{Rails.root}/public/403.html", status: :forbidden
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]

  def index
    @patients = Patient.all
  end

  def show; end

  def new
    @patient = Patient.new
  end

  def edit; end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patients_url, notice: 'Patient was successfully created.'
    else
      flash[:alert] = @patient.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_url(@patient), notice: 'Patient was successfully updated.'
    else
      flash[:alert] = @patient.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @patient.destroy

    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  def registration_progress
    @progress = Patient.group("DATE(created_at)").count
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:email, :full_name, :phone)
  end
end

app/controllers/receptionist_controller.rb
class ReceptionistController < ApplicationController
  before_action :set_receptionist
  before_action :authorize_user

  def edit; end

  def update
    if @receptionist.update(receptionist_params)
      flash[:notice] = 'Receptionist credentials updated'
      redirect_to edit_receptionist_path
    else
      flash[:notice] = @receptionist.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def receptionist_params
    params.require(:user).permit(:email, :password)
  end

  def set_receptionist
    @receptionist = User.find_by(role: :receptionist)
  end

  def authorize_user
    user_not_authorized unless current_user.doctor?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notices
    return notice if notice.is_a? Array

    [notice]
  end

  def alerts
    return alert if alert.is_a? Array

    [alert]
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/receptionist_helper.rb
module ReceptionistHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkerablSolution</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">/-</a>
        <% if current_user %>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Patients", patients_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Progress", registration_progress_patients_path, class:"nav-link" %>
              </li>
            </ul>
            <ul class="nav text-body-secondary">
              <li class="nav-item dropdown">
                <label class="nav-item" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  <%= current_user.email %>
                </label>
                <ul class="dropdown-menu">
                  <% if current_user&.doctor? %>
                    <li>
                      <%= link_to "Receptionist", edit_receptionist_path, class: 'dropdown-item' %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </nav>

    <div class=" position-absolute top-50 end-0">
      <% if notice %>
        <% notices.each do |message| %>
          <div class="p-3 bg-warning bg-opacity-10 border border-warning border-end-0 rounded-end mb-2">
            <%= message %>
          </div>
        <% end %>
      <% end %>
      <% if alert %>
        <% alerts.each do |message| %>
          <div class="p-3 bg-danger bg-opacity-10 border border-danger border-end-0 rounded-end mb-2">
            <%= message %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="w-75 m-auto mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= title %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <span class="me-auto"></span>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Back to Patients", patients_path, class: 'btn btn-link text-decoration-none m-1' %>
        </li>
        <li class="nav-item">
          <%= link_to "New patient", new_patient_path, class: 'btn btn-link text-decoration-none m-1' %>
        </li>
        <% if patient&.id %>
          <li class="nav-item">
            <%= link_to "Edit this patient", edit_patient_path(patient), class: 'btn btn-link text-decoration-none m-1' %>
          </li>
          <li class="nav-item">
            <%= button_to "Delete Patient", patient, method: :delete, class: 'btn btn-danger m-1' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/patients/_patient.html.erb
<tr>
  <th><%= link_to patient.full_name, patient, class: 'text-decoration-none' %></th>
  <td><%= patient.email %></td>
  <td><%= patient.phone %></td>
</tr>

app/views/patients/edit.html.erb
<%= render 'navbar', title: 'Edit Patient', patient: @patient %>

<%= render "form", patient: @patient %>

app/views/patients/index.html.erb
<%= render 'navbar', title: 'Patients', patient: nil %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <%= render patient %>
    <% end %>
  </tbody>
</table>

app/views/patients/new.html.erb
<%= render 'navbar', title: 'New Patient', patient: @patient %>

<%= render "form", patient: @patient %>

app/views/patients/registration_progress.html.erb
<%= render 'navbar', title: 'Patient Details', patient: nil %>

<%= line_chart @progress %>

app/views/patients/show.html.erb
<%= render 'navbar', title: 'Patient Details', patient: @patient %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
    </tr>
  </thead>
  <tbody>
    <%= render @patient %>
  </tbody>
</table

app/views/receptionist/edit.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Edit Receptionist</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <span class="me-auto"></span>
      <ul class="navbar-nav">
      </ul>
    </div>
  </div>
</nav>

<%= form_with(model: @receptionist, url: receptionist_path, method: :patch) do |form| %>
  <div class="container text-left">
    <div class="row">
      <div class="col">
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
        <%= form.hidden_field :id %>
      </div>
      <div class="col">
        <%= form.label :password, style: "display: block" %>
        <%= form.password_field :password %>
      </div>
    </div>
    <div class="row">
      <div class="col p-3">
        <%= form.submit 'Update Credentials' %>
      </div>
    </div>
  </div>
<% end %>